### ISSUE TITLE
Repeated styles

### ISSUE THREAD

**Issue by ghost** [ldelgadoIII/prj-rev-bwfs-dasmoto#3]
https://github.com/ldelgadoIII/prj-rev-bwfs-dasmoto/blob/master/Dasmoto's%20Arts%20%26%20Crafts/resources/css/style.css#L6

Avoid repeating yourself wherever possible. If you have styles that appear in multiple CSS rules, like the Helvetica font or text-align, try to move those styles into a single rule with multiple selectors. 

For example:

```css
h1, h2, h3, p {
  font-family: Helvetica;
}
```

Or in this case, if you know a style is going to apply to every single element on the page, you can use the universal selector `*`:

```css
* {
  font-family: Helvetica;
}
```

Make sure you refactor your CSS file at every opportunity, or it will become impossible to maintain as your website becomes more complex.
